---
abstract: 'Fix as much of Perl 5 as possible in one pragma'
author:
  - 'Michael G Schwern <schwern@pobox.com>'
build_requires:
  ExtUtils::CBuilder: 0.26
  IPC::Open3: 0
  Test::Exception: 0.27
  Test::More: 0.88
  Test::Output: 0.16
  Test::Warn: 0.11
configure_requires:
  Module::Build: 0.32
generated_by: 'Module::Build version 0.3601'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: perl5i
no_index:
  file:
    - lib/perl5i/0/DateTime.pm
    - lib/perl5i/0/ARRAY.pm
    - lib/perl5i/0/DEFAULT.pm
    - lib/perl5i/0/HASH.pm
    - lib/perl5i/0/Meta.pm
    - lib/perl5i/0/Meta/Class.pm
    - lib/perl5i/0/Meta/Instance.pm
    - lib/perl5i/0/SCALAR.pm
    - lib/perl5i/VERSION.pm
provides:
  DateTime::Format::CTime:
    file: lib/perl5i/0/DateTime.pm
  DateTime::time:
    file: lib/perl5i/0/DateTime.pm
  DateTime::y2038:
    file: lib/perl5i/0/DateTime.pm
  perl5i:
    file: lib/perl5i.pm
    version: v1.1.0
  perl5i::0:
    file: lib/perl5i/0.pm
    version: v1.1.0
  perl5i::0::ARRAY:
    file: lib/perl5i/0/ARRAY.pm
  perl5i::0::DEFAULT:
    file: lib/perl5i/0/DEFAULT.pm
  perl5i::0::DateTime:
    file: lib/perl5i/0/DateTime.pm
  perl5i::0::HASH:
    file: lib/perl5i/0/HASH.pm
  perl5i::0::Meta:
    file: lib/perl5i/0/Meta.pm
  perl5i::0::Meta::Class:
    file: lib/perl5i/0/Meta/Class.pm
  perl5i::0::Meta::Instance:
    file: lib/perl5i/0/Meta/Instance.pm
  perl5i::0::SCALAR:
    file: lib/perl5i/0/SCALAR.pm
  perl5i::1:
    file: lib/perl5i/1.pm
    version: v1.1.0
  perl5i::1::ARRAY:
    file: lib/perl5i/1/ARRAY.pm
  perl5i::1::CODE:
    file: lib/perl5i/1/CODE.pm
  perl5i::1::DateTime:
    file: lib/perl5i/1/DateTime.pm
  perl5i::1::HASH:
    file: lib/perl5i/1/HASH.pm
  perl5i::1::Meta:
    file: lib/perl5i/1/Meta.pm
  perl5i::1::Meta::Class:
    file: lib/perl5i/1/Meta/Class.pm
  perl5i::1::Meta::Instance:
    file: lib/perl5i/1/Meta/Instance.pm
  perl5i::1::SCALAR:
    file: lib/perl5i/1/SCALAR.pm
  perl5i::1::UNIVERSAL:
    file: lib/perl5i/1/UNIVERSAL.pm
  perl5i::1::autobox:
    file: lib/perl5i/1/autobox.pm
  perl5i::VERSION:
    file: lib/perl5i/VERSION.pm
    version: v1.1.0
  perl5i::latest:
    file: lib/perl5i/latest.pm
    version: v1.1.0
requires:
  CLASS: 1.00
  DateTime: 0.47
  DateTime::Format::Epoch: 0.11
  DateTime::TimeZone::Tzfile: 0.002
  File::chdir: 0.1002
  Hash::Merge::Simple: 0.04
  IPC::System::Simple: 1.18
  List::MoreUtils: 0.22
  Modern::Perl: 1.03
  Module::Load: 0.16
  Perl6::Caller: 0.100
  Taint::Util: 0.06
  Text::Wrap: 2009.0305
  Time::y2038: 20100218
  Try::Tiny: 0.02
  Want: 0.18
  autobox::Core: 0.6
  autobox::List::Util: 20090629
  autobox::dump: 20090426
  autodie: 1.999
  autovivification: 0.04
  parent: 0.221
  perl: v5.10.0
  version: 0.77
resources:
  Chat: irc://irc.perl.org/#perl5i
  MailingList: http://groups.google.com/group/perl5i
  bugtracker: http://github.com/schwern/perl5i/issues
  license: http://dev.perl.org/licenses/
  repository: http://github.com/schwern/perl5i/tree/master
version: v1.1.0
